# Generated by Django 6.0 on 2025-12-22 15:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Doctor's full name", max_length=50),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Doctor's email address", max_length=254
                    ),
                ),
                ("dob", models.DateField(help_text="Date of birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        help_text="Doctor's gender",
                        max_length=10,
                    ),
                ),
                (
                    "address",
                    models.TextField(help_text="Doctor's complete residential address"),
                ),
                (
                    "mobile_no",
                    models.CharField(
                        help_text="10-digit mobile number",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit mobile number starting with 6,7,8 or 9",
                                regex="^[6789]\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "registration_no",
                    models.CharField(
                        help_text="Medical registration number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "year_of_registration",
                    models.DateField(help_text="Year of medical registration"),
                ),
                (
                    "qualification",
                    models.CharField(
                        help_text="Medical qualification (e.g., MBBS, MD, MS)",
                        max_length=50,
                    ),
                ),
                (
                    "State_Medical_Council",
                    models.CharField(
                        help_text="State Medical Council name", max_length=50
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("Rheumatologist", "Rheumatologist"),
                            ("Cardiologist", "Cardiologist"),
                            ("ENT specialist", "ENT Specialist"),
                            ("Orthopedist", "Orthopedist"),
                            ("Neurologist", "Neurologist"),
                            ("Allergist/Immunologist", "Allergist/Immunologist"),
                            ("Urologist", "Urologist"),
                            ("Dermatologist", "Dermatologist"),
                            ("Gastroenterologist", "Gastroenterologist"),
                            ("General Physician", "General Physician"),
                            ("Pediatrician", "Pediatrician"),
                            ("Psychiatrist", "Psychiatrist"),
                            ("Oncologist", "Oncologist"),
                            ("Ophthalmologist", "Ophthalmologist"),
                            ("Other", "Other"),
                        ],
                        help_text="Medical specialization",
                        max_length=30,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether doctor's credentials are verified",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Whether doctor is currently available for appointments",
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        default=0, help_text="Years of medical experience"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "ordering": ["-created_at"],
                "unique_together": {("registration_no",)},
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Patient's full name", max_length=50),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Patient's email address", max_length=254
                    ),
                ),
                ("dob", models.DateField(help_text="Date of birth")),
                ("age", models.PositiveIntegerField(help_text="Patient's age")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        help_text="Patient's gender",
                        max_length=10,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Patient's complete residential address"
                    ),
                ),
                (
                    "mobile_no",
                    models.CharField(
                        help_text="10-digit mobile number",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit mobile number starting with 6,7,8 or 9",
                                regex="^[6789]\\d{9}$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(help_text="Type of medical record", max_length=50),
                ),
                ("diagnosis", models.TextField(help_text="Medical diagnosis")),
                ("treatment", models.TextField(help_text="Treatment provided")),
                (
                    "prescription",
                    models.TextField(blank=True, help_text="Prescription details"),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "record_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date of medical record",
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateTimeField(
                        blank=True, help_text="Follow-up appointment date", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_confidential",
                    models.BooleanField(
                        default=True, help_text="Whether record is confidential"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="accounts.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="accounts.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record",
                "verbose_name_plural": "Medical Records",
                "ordering": ["-record_date"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="User profile picture",
                        null=True,
                        upload_to="profile_pics/",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="User biography or description"
                    ),
                ),
                (
                    "notification_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User notification preferences",
                    ),
                ),
                (
                    "privacy_settings",
                    models.JSONField(
                        blank=True, default=dict, help_text="User privacy settings"
                    ),
                ),
                (
                    "is_profile_complete",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user has completed their profile",
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, help_text="Last login IP address", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_date",
                    models.DateTimeField(
                        help_text="Scheduled appointment date and time"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=30, help_text="Appointment duration in minutes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=15,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for appointment")),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional appointment notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="accounts.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="accounts.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "ordering": ["appointment_date"],
                "unique_together": {("doctor", "appointment_date")},
            },
        ),
    ]
